import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class Damage {
    /**
     * A map that stores the effectiveness factors of different type combinations.
     */
    final private static Map<String, Double> attackDefenseMap = new HashMap<>();

    // Static block to initialize the attackDefenseMap with effectiveness factors
    static {
        attackDefenseMap.put("WaterWater", 0.5);
        attackDefenseMap.put("WaterFighting", 1.0);
        attackDefenseMap.put("WaterRock", 2.0);
        attackDefenseMap.put("WaterGround", 2.0);
        attackDefenseMap.put("WaterElectric", 1.0);
        attackDefenseMap.put("WaterIce", 1.0);
        attackDefenseMap.put("WaterGrass", 0.5);
        attackDefenseMap.put("WaterNormal", 1.0);
        attackDefenseMap.put("WaterSteel", 1.0);
        attackDefenseMap.put("WaterDragon", 0.5);
        attackDefenseMap.put("WaterFlying", 1.0);
        attackDefenseMap.put("WaterPsychic", 1.0);
        attackDefenseMap.put("WaterBug", 1.0);
        attackDefenseMap.put("WaterGhost", 1.0);
        attackDefenseMap.put("WaterDark", 1.0);
        attackDefenseMap.put("WaterFire", 2.0);
        attackDefenseMap.put("WaterPoison", 1.0);
        attackDefenseMap.put("WaterFairy", 1.0);
        attackDefenseMap.put("FightingWater", 1.0);
        attackDefenseMap.put("FightingFighting", 1.0);
        attackDefenseMap.put("FightingRock", 2.0);
        attackDefenseMap.put("FightingGround", 1.0);
        attackDefenseMap.put("FightingElectric", 1.0);
        attackDefenseMap.put("FightingIce", 2.0);
        attackDefenseMap.put("FightingGrass", 1.0);
        attackDefenseMap.put("FightingNormal", 2.0);
        attackDefenseMap.put("FightingSteel", 2.0);
        attackDefenseMap.put("FightingDragon", 1.0);
        attackDefenseMap.put("FightingFlying", 0.5);
        attackDefenseMap.put("FightingPsychic", 0.5);
        attackDefenseMap.put("FightingBug", 0.5);
        attackDefenseMap.put("FightingGhost", 0.0);
        attackDefenseMap.put("FightingDark", 2.0);
        attackDefenseMap.put("FightingFire", 1.0);
        attackDefenseMap.put("FightingPoison", 0.5);
        attackDefenseMap.put("FightingFairy", 0.5);
        attackDefenseMap.put("RockWater", 1.0);
        attackDefenseMap.put("RockFighting", 0.5);
        attackDefenseMap.put("RockRock", 1.0);
        attackDefenseMap.put("RockGround", 0.5);
        attackDefenseMap.put("RockElectric", 1.0);
        attackDefenseMap.put("RockIce", 2.0);
        attackDefenseMap.put("RockGrass", 1.0);
        attackDefenseMap.put("RockNormal", 1.0);
        attackDefenseMap.put("RockSteel", 0.5);
        attackDefenseMap.put("RockDragon", 1.0);
        attackDefenseMap.put("RockFlying", 2.0);
        attackDefenseMap.put("RockPsychic", 1.0);
        attackDefenseMap.put("RockBug", 2.0);
        attackDefenseMap.put("RockGhost", 1.0);
        attackDefenseMap.put("RockDark", 1.0);
        attackDefenseMap.put("RockFire", 0.5);
        attackDefenseMap.put("RockPoison", 1.0);
        attackDefenseMap.put("RockFairy", 1.0);
        attackDefenseMap.put("GroundWater", 1.0);
        attackDefenseMap.put("GroundFighting", 1.0);
        attackDefenseMap.put("GroundRock", 2.0);
        attackDefenseMap.put("GroundGround", 1.0);
        attackDefenseMap.put("GroundElectric", 2.0);
        attackDefenseMap.put("GroundIce", 1.0);
        attackDefenseMap.put("GroundGrass", 0.5);
        attackDefenseMap.put("GroundNormal", 1.0);
        attackDefenseMap.put("GroundSteel", 2.0);
        attackDefenseMap.put("GroundDragon", 1.0);
        attackDefenseMap.put("GroundFlying", 0.0);
        attackDefenseMap.put("GroundPsychic", 1.0);
        attackDefenseMap.put("GroundBug", 0.5);
        attackDefenseMap.put("GroundGhost", 1.0);
        attackDefenseMap.put("GroundDark", 1.0);
        attackDefenseMap.put("GroundFire", 2.0);
        attackDefenseMap.put("GroundPoison", 2.0);
        attackDefenseMap.put("GroundFairy", 1.0);
        attackDefenseMap.put("ElectricWater", 2.0);
        attackDefenseMap.put("ElectricFighting", 1.0);
        attackDefenseMap.put("ElectricRock", 1.0);
        attackDefenseMap.put("ElectricGround", 0.0);
        attackDefenseMap.put("ElectricElectric", 0.5);
        attackDefenseMap.put("ElectricIce", 1.0);
        attackDefenseMap.put("ElectricGrass", 0.5);
        attackDefenseMap.put("ElectricNormal", 1.0);
        attackDefenseMap.put("ElectricSteel", 1.0);
        attackDefenseMap.put("ElectricDragon", 0.5);
        attackDefenseMap.put("ElectricFlying", 2.0);
        attackDefenseMap.put("ElectricPsychic", 1.0);
        attackDefenseMap.put("ElectricBug", 1.0);
        attackDefenseMap.put("ElectricGhost", 1.0);
        attackDefenseMap.put("ElectricDark", 1.0);
        attackDefenseMap.put("ElectricFire", 1.0);
        attackDefenseMap.put("ElectricPoison", 1.0);
        attackDefenseMap.put("ElectricFairy", 1.0);
        attackDefenseMap.put("IceWater", 0.5);
        attackDefenseMap.put("IceFighting", 1.0);
        attackDefenseMap.put("IceRock", 1.0);
        attackDefenseMap.put("IceGround", 2.0);
        attackDefenseMap.put("IceElectric", 1.0);
        attackDefenseMap.put("IceIce", 0.5);
        attackDefenseMap.put("IceGrass", 2.0);
        attackDefenseMap.put("IceNormal", 1.0);
        attackDefenseMap.put("IceSteel", 0.5);
        attackDefenseMap.put("IceDragon", 2.0);
        attackDefenseMap.put("IceFlying", 2.0);
        attackDefenseMap.put("IcePsychic", 1.0);
        attackDefenseMap.put("IceBug", 1.0);
        attackDefenseMap.put("IceGhost", 1.0);
        attackDefenseMap.put("IceDark", 1.0);
        attackDefenseMap.put("IceFire", 0.5);
        attackDefenseMap.put("IcePoison", 1.0);
        attackDefenseMap.put("IceFairy", 1.0);
        attackDefenseMap.put("GrassWater", 2.0);
        attackDefenseMap.put("GrassFighting", 1.0);
        attackDefenseMap.put("GrassRock", 2.0);
        attackDefenseMap.put("GrassGround", 2.0);
        attackDefenseMap.put("GrassElectric", 1.0);
        attackDefenseMap.put("GrassIce", 1.0);
        attackDefenseMap.put("GrassGrass", 0.5);
        attackDefenseMap.put("GrassNormal", 1.0);
        attackDefenseMap.put("GrassSteel", 0.5);
        attackDefenseMap.put("GrassDragon", 0.5);
        attackDefenseMap.put("GrassFlying", 0.5);
        attackDefenseMap.put("GrassPsychic", 1.0);
        attackDefenseMap.put("GrassBug", 0.5);
        attackDefenseMap.put("GrassGhost", 1.0);
        attackDefenseMap.put("GrassDark", 1.0);
        attackDefenseMap.put("GrassFire", 0.5);
        attackDefenseMap.put("GrassPoison", 0.5);
        attackDefenseMap.put("GrassFairy", 1.0);
        attackDefenseMap.put("NormalWater", 1.0);
        attackDefenseMap.put("NormalFighting", 1.0);
        attackDefenseMap.put("NormalRock", 0.5);
        attackDefenseMap.put("NormalGround", 1.0);
        attackDefenseMap.put("NormalElectric", 1.0);
        attackDefenseMap.put("NormalIce", 1.0);
        attackDefenseMap.put("NormalGrass", 1.0);
        attackDefenseMap.put("NormalNormal", 1.0);
        attackDefenseMap.put("NormalSteel", 0.5);
        attackDefenseMap.put("NormalDragon", 1.0);
        attackDefenseMap.put("NormalFlying", 1.0);
        attackDefenseMap.put("NormalPsychic", 1.0);
        attackDefenseMap.put("NormalBug", 1.0);
        attackDefenseMap.put("NormalGhost", 0.0);
        attackDefenseMap.put("NormalDark", 1.0);
        attackDefenseMap.put("NormalFire", 1.0);
        attackDefenseMap.put("NormalPoison", 1.0);
        attackDefenseMap.put("NormalFairy", 1.0);
        attackDefenseMap.put("SteelWater", 0.5);
        attackDefenseMap.put("SteelFighting", 1.0);
        attackDefenseMap.put("SteelRock", 2.0);
        attackDefenseMap.put("SteelGround", 1.0);
        attackDefenseMap.put("SteelElectric", 0.5);
        attackDefenseMap.put("SteelIce", 2.0);
        attackDefenseMap.put("SteelGrass", 1.0);
        attackDefenseMap.put("SteelNormal", 1.0);
        attackDefenseMap.put("SteelSteel", 0.5);
        attackDefenseMap.put("SteelDragon", 1.0);
        attackDefenseMap.put("SteelFlying", 1.0);
        attackDefenseMap.put("SteelPsychic", 1.0);
        attackDefenseMap.put("SteelBug", 1.0);
        attackDefenseMap.put("SteelGhost", 1.0);
        attackDefenseMap.put("SteelDark", 1.0);
        attackDefenseMap.put("SteelFire", 0.5);
        attackDefenseMap.put("SteelPoison", 1.0);
        attackDefenseMap.put("SteelFairy", 2.0);
        attackDefenseMap.put("DragonWater", 1.0);
        attackDefenseMap.put("DragonFighting", 1.0);
        attackDefenseMap.put("DragonRock", 1.0);
        attackDefenseMap.put("DragonGround", 1.0);
        attackDefenseMap.put("DragonElectric", 1.0);
        attackDefenseMap.put("DragonIce", 1.0);
        attackDefenseMap.put("DragonGrass", 1.0);
        attackDefenseMap.put("DragonNormal", 1.0);
        attackDefenseMap.put("DragonSteel", 0.5);
        attackDefenseMap.put("DragonDragon", 2.0);
        attackDefenseMap.put("DragonFlying", 1.0);
        attackDefenseMap.put("DragonPsychic", 1.0);
        attackDefenseMap.put("DragonBug", 1.0);
        attackDefenseMap.put("DragonGhost", 1.0);
        attackDefenseMap.put("DragonDark", 1.0);
        attackDefenseMap.put("DragonFire", 1.0);
        attackDefenseMap.put("DragonPoison", 1.0);
        attackDefenseMap.put("DragonFairy", 0.0);
        attackDefenseMap.put("FlyingWater", 1.0);
        attackDefenseMap.put("FlyingFighting", 2.0);
        attackDefenseMap.put("FlyingRock", 0.5);
        attackDefenseMap.put("FlyingGround", 1.0);
        attackDefenseMap.put("FlyingElectric", 0.5);
        attackDefenseMap.put("FlyingIce", 1.0);
        attackDefenseMap.put("FlyingGrass", 2.0);
        attackDefenseMap.put("FlyingNormal", 1.0);
        attackDefenseMap.put("FlyingSteel", 0.5);
        attackDefenseMap.put("FlyingDragon", 1.0);
        attackDefenseMap.put("FlyingFlying", 1.0);
        attackDefenseMap.put("FlyingPsychic", 1.0);
        attackDefenseMap.put("FlyingBug", 2.0);
        attackDefenseMap.put("FlyingGhost", 1.0);
        attackDefenseMap.put("FlyingDark", 1.0);
        attackDefenseMap.put("FlyingFire", 1.0);
        attackDefenseMap.put("FlyingPoison", 1.0);
        attackDefenseMap.put("FlyingFairy", 1.0);
        attackDefenseMap.put("PsychicWater", 1.0);
        attackDefenseMap.put("PsychicFighting", 2.0);
        attackDefenseMap.put("PsychicRock", 1.0);
        attackDefenseMap.put("PsychicGround", 1.0);
        attackDefenseMap.put("PsychicElectric", 1.0);
        attackDefenseMap.put("PsychicIce", 1.0);
        attackDefenseMap.put("PsychicGrass", 1.0);
        attackDefenseMap.put("PsychicNormal", 1.0);
        attackDefenseMap.put("PsychicSteel", 0.5);
        attackDefenseMap.put("PsychicDragon", 1.0);
        attackDefenseMap.put("PsychicFlying", 1.0);
        attackDefenseMap.put("PsychicPsychic", 0.5);
        attackDefenseMap.put("PsychicBug", 1.0);
        attackDefenseMap.put("PsychicGhost", 1.0);
        attackDefenseMap.put("PsychicDark", 0.0);
        attackDefenseMap.put("PsychicFire", 1.0);
        attackDefenseMap.put("PsychicPoison", 2.0);
        attackDefenseMap.put("PsychicFairy", 1.0);
        attackDefenseMap.put("BugWater", 1.0);
        attackDefenseMap.put("BugFighting", 0.5);
        attackDefenseMap.put("BugRock", 1.0);
        attackDefenseMap.put("BugGround", 1.0);
        attackDefenseMap.put("BugElectric", 1.0);
        attackDefenseMap.put("BugIce", 1.0);
        attackDefenseMap.put("BugGrass", 2.0);
        attackDefenseMap.put("BugNormal", 1.0);
        attackDefenseMap.put("BugSteel", 0.5);
        attackDefenseMap.put("BugDragon", 1.0);
        attackDefenseMap.put("BugFlying", 0.5);
        attackDefenseMap.put("BugPsychic", 2.0);
        attackDefenseMap.put("BugBug", 1.0);
        attackDefenseMap.put("BugGhost", 0.5);
        attackDefenseMap.put("BugDark", 2.0);
        attackDefenseMap.put("BugFire", 0.5);
        attackDefenseMap.put("BugPoison", 0.5);
        attackDefenseMap.put("BugFairy", 0.5);
        attackDefenseMap.put("GhostWater", 1.0);
        attackDefenseMap.put("GhostFighting", 1.0);
        attackDefenseMap.put("GhostRock", 1.0);
        attackDefenseMap.put("GhostGround", 1.0);
        attackDefenseMap.put("GhostElectric", 1.0);
        attackDefenseMap.put("GhostIce", 1.0);
        attackDefenseMap.put("GhostGrass", 1.0);
        attackDefenseMap.put("GhostNormal", 0.0);
        attackDefenseMap.put("GhostSteel", 1.0);
        attackDefenseMap.put("GhostDragon", 1.0);
        attackDefenseMap.put("GhostFlying", 1.0);
        attackDefenseMap.put("GhostPsychic", 2.0);
        attackDefenseMap.put("GhostBug", 1.0);
        attackDefenseMap.put("GhostGhost", 2.0);
        attackDefenseMap.put("GhostDark", 0.5);
        attackDefenseMap.put("GhostFire", 1.0);
        attackDefenseMap.put("GhostPoison", 1.0);
        attackDefenseMap.put("GhostFairy", 1.0);
        attackDefenseMap.put("DarkWater", 1.0);
        attackDefenseMap.put("DarkFighting", 0.5);
        attackDefenseMap.put("DarkRock", 1.0);
        attackDefenseMap.put("DarkGround", 1.0);
        attackDefenseMap.put("DarkElectric", 1.0);
        attackDefenseMap.put("DarkIce", 1.0);
        attackDefenseMap.put("DarkGrass", 1.0);
        attackDefenseMap.put("DarkNormal", 1.0);
        attackDefenseMap.put("DarkSteel", 1.0);
        attackDefenseMap.put("DarkDragon", 1.0);
        attackDefenseMap.put("DarkFlying", 1.0);
        attackDefenseMap.put("DarkPsychic", 2.0);
        attackDefenseMap.put("DarkBug", 1.0);
        attackDefenseMap.put("DarkGhost", 2.0);
        attackDefenseMap.put("DarkDark", 0.5);
        attackDefenseMap.put("DarkFire", 1.0);
        attackDefenseMap.put("DarkPoison", 1.0);
        attackDefenseMap.put("DarkFairy", 0.5);
        attackDefenseMap.put("FireWater", 0.5);
        attackDefenseMap.put("FireFighting", 1.0);
        attackDefenseMap.put("FireRock", 0.5);
        attackDefenseMap.put("FireGround", 1.0);
        attackDefenseMap.put("FireElectric", 1.0);
        attackDefenseMap.put("FireIce", 2.0);
        attackDefenseMap.put("FireGrass", 2.0);
        attackDefenseMap.put("FireNormal", 1.0);
        attackDefenseMap.put("FireSteel", 2.0);
        attackDefenseMap.put("FireDragon", 0.5);
        attackDefenseMap.put("FireFlying", 1.0);
        attackDefenseMap.put("FirePsychic", 1.0);
        attackDefenseMap.put("FireBug", 2.0);
        attackDefenseMap.put("FireGhost", 1.0);
        attackDefenseMap.put("FireDark", 1.0);
        attackDefenseMap.put("FireFire", 0.5);
        attackDefenseMap.put("FirePoison", 1.0);
        attackDefenseMap.put("FireFairy", 1.0);
        attackDefenseMap.put("PoisonWater", 1.0);
        attackDefenseMap.put("PoisonFighting", 1.0);
        attackDefenseMap.put("PoisonRock", 0.5);
        attackDefenseMap.put("PoisonGround", 0.5);
        attackDefenseMap.put("PoisonElectric", 1.0);
        attackDefenseMap.put("PoisonIce", 1.0);
        attackDefenseMap.put("PoisonGrass", 2.0);
        attackDefenseMap.put("PoisonNormal", 1.0);
        attackDefenseMap.put("PoisonSteel", 0.0);
        attackDefenseMap.put("PoisonDragon", 1.0);
        attackDefenseMap.put("PoisonFlying", 1.0);
        attackDefenseMap.put("PoisonPsychic", 1.0);
        attackDefenseMap.put("PoisonBug", 1.0);
        attackDefenseMap.put("PoisonGhost", 0.5);
        attackDefenseMap.put("PoisonDark", 1.0);
        attackDefenseMap.put("PoisonFire", 1.0);
        attackDefenseMap.put("PoisonPoison", 0.5);
        attackDefenseMap.put("PoisonFairy", 2.0);
        attackDefenseMap.put("FairyWater", 1.0);
        attackDefenseMap.put("FairyFighting", 2.0);
        attackDefenseMap.put("FairyRock", 1.0);
        attackDefenseMap.put("FairyGround", 1.0);
        attackDefenseMap.put("FairyElectric", 1.0);
        attackDefenseMap.put("FairyIce", 1.0);
        attackDefenseMap.put("FairyGrass", 1.0);
        attackDefenseMap.put("FairyNormal", 1.0);
        attackDefenseMap.put("FairySteel", 0.5);
        attackDefenseMap.put("FairyDragon", 2.0);
        attackDefenseMap.put("FairyFlying", 1.0);
        attackDefenseMap.put("FairyPsychic", 1.0);
        attackDefenseMap.put("FairyBug", 1.0);
        attackDefenseMap.put("FairyGhost", 1.0);
        attackDefenseMap.put("FairyDark", 2.0);
        attackDefenseMap.put("FairyFire", 0.5);
        attackDefenseMap.put("FairyPoison", 0.5);
        attackDefenseMap.put("FairyFairy", 1.0);
    }

    /**
     * Returns the effectiveness factor of an attacking type against a defending type.
     *
     * @param attackingType the type of the attacking entity
     * @param defendingType the type of the defending entity
     * @return the effectiveness factor of the attacking type against the defending type
     */
    public static double getFactor(String attackingType, String defendingType) {
        return attackDefenseMap.get(attackingType + defendingType);
    }

    static public int getDamage(PokemonFinal attacker, PokemonFinal defender) {
        double attackerLevel = (double) attacker.getLevel();
        double attackPower = (double) attacker.getPower();
        double attack = (double) attacker.getAttack();
        double defense = (double) defender.getDefence();

        Random random = new Random();
        double criticalHit = (double) random.nextInt(2) + 1; // Generates either 1 or 2
        if (criticalHit == 2) {
            System.out.println("This is super effective!");
        }
        double effectivenessFactor = Damage.getFactor(attacker.getType(), defender.getType());
        return (int) ((((2 * attackerLevel * criticalHit) / 5 + 2) * attackPower * attack / defense / 50 + 2) * effectivenessFactor * 0.5);
    }
}